version: "3.3"
services:
  iris:
    build:
      context: .
    container_name: npm-iris
    command: --check-caps false
    ports:
      - 1972
      - 52773:52773
      - 53773
    volumes:
      - ./src/csp:/opt/irisapp/csp
      - ./:/irisdev/app
