version: "3.3"
services:
  iris:
    build:
      context: .
    container_name: npm-iris
    comand: --check-caps false
    ports:
      - 51773
      - ${IRIS_PORT}:52773
      - 53773
    volumes:
      - ./src/csp:/opt/irisapp/csp
      - ./:/irisdev/app
